{% set version = "0.2.10" %}
{% set python_min = "3.10.0" %}

package:
  name: image-registration
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/image-registration/image_registration-{{ version }}.tar.gz
  sha256: b1798265947204ea95516b4e48e9f78bb25103734ab5a22922011eca825fe459

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - astropy-package-template-example = packagename.example_mod:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - extension-helpers
    - numpy
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base
    - matplotlib-base
    - pytest

test:
  imports:
    - image_registration
  commands:
    - pip check
    - astropy-package-template-example --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://image-registration.readthedocs.io/en/latest/
  summary: Package for registering images with extended emission
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tcompa
